<?xml version="1.0" encoding="utf-8"?><Database Class="LinqToSqlDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="" Member="Customers">
    <Type Name="Customer">
      <Column Name="Id" Type="System.Int32" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" CanBeNull="false" />
      <Association Name="Customer_Order" Member="Orders" ThisKey="Id" OtherKey="ProductId" Type="Order" />
    </Type>
  </Table>
  <Table Name="" Member="Products">
    <Type Name="Product">
      <Column Member="Id" Type="System.Int32" IsPrimaryKey="true" CanBeNull="false" />
      <Column Member="Name" Type="System.String" CanBeNull="false" />
      <Column Member="Price" Type="System.Double" CanBeNull="false" />
      <Association Name="Product_Order" Member="Orders" ThisKey="Id" OtherKey="ProductId" Type="Order" />
    </Type>
  </Table>
  <Table Name="" Member="Orders">
    <Type Name="Order">
      <Column Member="Id" Type="System.Int32" IsPrimaryKey="true" CanBeNull="false" />
      <Column Member="ProductId" Type="System.Int32" CanBeNull="false" />
      <Column Member="Amount" Type="System.UInt32" CanBeNull="false" />
      <Column Member="CustomerId" Type="System.Int32" CanBeNull="false" />
      <Association Name="Customer_Order" Member="Customer" ThisKey="ProductId" OtherKey="Id" Type="Customer" IsForeignKey="true" />
      <Association Name="Product_Order" Member="Product" ThisKey="ProductId" OtherKey="Id" Type="Product" IsForeignKey="true" />
    </Type>
  </Table>
</Database>